---
apiVersion: v1
kind: Namespace
metadata:
  name: hasbrain

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flownote
  namespace: hasbrain

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: flownote
  namespace: hasbrain
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets", "configmaps"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions",  "apps"]
  resources: ["ingresses", "deployments", "daemonsets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: flownote
  namespace: hasbrain
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flownote
subjects:
- kind: ServiceAccount
  name: flownote